### ISSUE TITLE
Accessibility: usage of "visuallyhidden" CSS class results in a pa11y warning

### ISSUE THREAD

**Issue by K-T-O** [CJSCommonPlatform/govuk_single_page_pdk#105]
Pa11y warns about the following issue:

- WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Abs

Warning: This element is absolutely positioned and the background color can not be determined. Ensure the contrast ratio between the text and all covered parts of the background are at least 4.5:1.

Which I guess does not make much sense but occurs due to:

@gov.uk/platform-template/lib/govuk_template/stylesheets/_accessibility.scss

/* Hide only visually, but have it available for screenreaders */
.visually-hidden,
.visuallyhidden {
  position: absolute;
  left: -9999em;

**Comment by fabiotisci** [comment]
this way of doing this comes from GDS so UX is aware of it.
