### ISSUE TITLE
Accessibility: gov-dataset generates anchor with no ID/href/name

### ISSUE THREAD

**Issue by K-T-O** [CJSCommonPlatform/govuk_single_page_pdk#107]
Pa11y warns about the following issue:

- WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.Placeholder

Warning: Anchor element found with link content, but no href, ID or name attribute has been supplied.

This occurs in the generated link in the gov-dataset module.

**Comment by fabiotisci** [comment]
Unfortunately this error won't be able to be fixed as it's particular of Angular, so it will need to be added to ignore.
