### ISSUE TITLE
How do we take care of CSS styles outside of components in PDK

### ISSUE THREAD

**Issue by Shaks** [CJSCommonPlatform/govuk_single_page_pdk#116]
![viewuploadederror](https://cloud.githubusercontent.com/assets/1534608/19643931/dfc9a4c8-99e4-11e6-9f3d-019ce54108fa.png)

**Comment by fabiotisci** [comment]
I don't really understand what you mean. Do you mean designs that use patterns not included in PDK?
Initially any approved design would go through design board, and if approved will be included in the CJS CPP design document... which later will be added to PDK.

**Comment by jamesbirrellgray** [comment]
@Shaks @trevorsaint - have you taken these patterns to deign board?

**Comment by jamesbirrellgray** [comment]
@Shaks

**Comment by scarlz** [comment]
Just going through and addressing some older issues:

Not all pages will require components, especially if the pages can be built using the styles provided by govuk-elements. The above screenshot seems like a good contender for this, in that it be built from a combination of tables, headings and buttons.

If a particular, recurring style were absent from govuk-elements, this is something we could then consider adding to PDK.
