### ISSUE TITLE
Date component does not look like GDS (GOV Elements)

### ISSUE THREAD

**Issue by trevorsaint** [CJSCommonPlatform/govuk_single_page_pdk#132]
The date style and html does not match what GDS have already created for us.

**What's in PDK**
http://cjscommonplatform.github.io/govuk_single_page_pdk/#/components/forms-and-errors

**What's in Gov elements**
http://govuk-elements.herokuapp.com/form-elements/example-date/

The html and css has already been done for us. Can we remove the additional styling and use GDS classes and html, so that it renders correctly accross the platform.

Thanks.

**Comment by scarlz** [comment]
Fixed in https://github.com/CJSCommonPlatform/govuk_single_page_pdk/commit/530ec53150791f167b3a89d64f14351ea4aa1066.
