### ISSUE TITLE
navigation/menus/side-menu

### ISSUE THREAD

**Issue by vygis** [CJSCommonPlatform/govuk_single_page_pdk#27]

**Comment by fabiotisci** [comment]
We need to limit the text of the description to max 3 lines. Please check this library... we can either re-use it or apply the same principle:
https://github.com/Coffa/angular-clamp

**Comment by vygis** [comment]
I'll have a look

**Comment by trevorsaint** [comment]
A serious case of 'Divitus'

**Comment by vygis** [comment]
I've now implemented the 3 line max rule on the PDK. In the end I created my own `ng-clamp` directive and published in via npm instead of using the one Fabio recommended, as it didn't really work. Note that `uiApp` will now need to include it. I will publish the repo via Bower to be used by `uiApp`
