### ISSUE TITLE
Accessibility: Horizontal link list

### ISSUE THREAD

**Issue by K-T-O** [CJSCommonPlatform/govuk_single_page_pdk#59]
Links with similar meaning should be grouped as a list (pa11y warning) to be easily skippable.
Currently in IDAM we use:
Link1 | Link2
![screen shot 2016-08-09 at 14 13 53](https://cloud.githubusercontent.com/assets/13416854/17517483/8e97db4a-5e3b-11e6-98dc-3d36eed3b1f1.png)

while it should be an ol/li with display: inline-block list with proper styling and padding as "|" is a character with no value to the content/meaning it's just a visualisation feature.

**Comment by fabiotisci** [comment]
Which PDK component is using this type of links? Please specify

**Comment by K-T-O** [comment]
To my knowledge no PDK component offers this kind of functionality. 
This issue is an enhancement request originated from requirements on IDAM.

**Comment by fabiotisci** [comment]
for anything to go on the PDK UX design board needs to approved, then go
into the CJS CPP Design document and after that can be included on PDK. So
I guess your designer will need to raise that on the design board meeting.

**Comment by blackmonday** [comment]
This isn’t a pattern that should be used going forward.

When the search users list filters story was originally worked on the “Filters” pattern hadn’t been finalised so the text links separated by a ‘|’ was used as a temporary solution until the pattern was added to the PDK. Please use the “Fitlers” pattern:

You can see the “Filtes” pattern as it should appear on page 11 of this PDF:
https://triadmoj.atlassian.net/wiki/download/attachments/55705917/IdAM_v2_Support_Admin_v1.3.4_search.pdf

You can find the “Filters” pattern  in the PDK here:
https://cjscommonplatform.github.io/govuk_single_page_pdk/#/components/data-visualisation#gov-filters-demo
