### ISSUE TITLE
Accessibility: contrast ratio - header

### ISSUE THREAD

**Issue by K-T-O** [CJSCommonPlatform/govuk_single_page_pdk#99]
Pa11y warns about the following issue:

- WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.BgImage

This element's text is placed on a background image. Ensure the contrast ratio between the text and all covered parts of the image are at least 4.5:1.

This relates to the following components [gov-header]: 
- Skip to main content 
- Go to the GOV.UK homepage

**Comment by fabiotisci** [comment]
UX are aware of this. The problem comes from Gov elements styles so it's not directly PDK
